name: Cerracore
favicon: null
layout_spectrum: 0.99382
typography_spectrum: 0.6472359888721257
title: cerracore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b3b3b'
    - '#f12a0d'
    - '#b5b5b5'
    - '#f45b44'
  brandStrength: 0.9375
  lightness: 0.7547787467483431
  saturation: 0.05538673582486808
  rhythmicContrast: 0.06222422025166452
purpose: []
