name: Cerracore
favicon: null
layout_spectrum: 0.32378
typography_spectrum: 0.6472359888721257
title: cerracore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12021869979798794
  lightness: 0.7547787467483431
  saturation: 0.05538673582486808
  rhythmicContrast: 0.06222422025166452
purpose: []
